// =============================================================================
// js/config/sectorsData.js
// Configuração central dos Setores Inteligentes (Fase 4 - Etapa 2)
// Extraído de app.js — NÃO alterar sem aprovação técnica.
// =============================================================================

const sectorsData = {
    'entrada': {
        nome: "Portaria",
        desc: "Portaria e Recepção Externa",
        funcoes: ["Portaria"],
        cor: "#127369",
        themeClass: "theme-diaconia",
        icon: "fa-solid fa-door-open",
        tipo: "liturgico",
        categoria: "liturgico",
        labelMembroSingular: "Obreiro",
        labelMembroPlural: "Obreiros",
        participaCulto: true,
        possuiEscala: true,
        possuiReposicao: false,
        possuiEstoque: false,
        possuiCheckinCulto: true,
        possuiFechamentoCulto: true,
        possuiInicioServico: false,
        possuiFimServico: false
    },
    'check_in': {
        nome: "Check-in",
        desc: "Validação de presença e controle de acesso",
        funcoes: ["Check-in"],
        cor: "#10403B",
        themeClass: "theme-diaconia",
        icon: "fa-solid fa-address-card",
        tipo: "liturgico",
        categoria: "liturgico",
        labelMembroSingular: "Obreiro",
        labelMembroPlural: "Obreiros",
        participaCulto: true,
        possuiEscala: true,
        possuiReposicao: false,
        possuiEstoque: false,
        possuiCheckinCulto: true,
        possuiFechamentoCulto: true,
        possuiInicioServico: false,
        possuiFimServico: false
    },
    'apoio_templo_ronda_dir': {
        nome: "Apoio Templo / Ronda Lado Direito",
        desc: "Diaconia interna e ronda no lado direito do templo",
        funcoes: ["Apoio Templo / Ronda Lado Direito"],
        cor: "#8AA6A3",
        themeClass: "theme-diaconia",
        icon: "fa-solid fa-chevron-right",
        tipo: "liturgico",
        categoria: "liturgico",
        labelMembroSingular: "Obreiro",
        labelMembroPlural: "Obreiros",
        participaCulto: true,
        possuiEscala: true,
        possuiReposicao: false,
        possuiEstoque: false,
        possuiCheckinCulto: true,
        possuiFechamentoCulto: true,
        possuiInicioServico: false,
        possuiFimServico: false
    },
    'apoio_templo_ronda_esq': {
        nome: "Apoio Templo / Ronda Lado Esquerdo",
        desc: "Diaconia interna e ronda no lado esquerdo do templo",
        funcoes: ["Apoio Templo / Ronda Lado Esquerdo"],
        cor: "#4C5958",
        themeClass: "theme-diaconia",
        icon: "fa-solid fa-chevron-left",
        tipo: "liturgico",
        categoria: "liturgico",
        labelMembroSingular: "Obreiro",
        labelMembroPlural: "Obreiros",
        participaCulto: true,
        possuiEscala: true,
        possuiReposicao: false,
        possuiEstoque: false,
        possuiCheckinCulto: true,
        possuiFechamentoCulto: true,
        possuiInicioServico: false,
        possuiFimServico: false
    },
    'acolhimento': {
        nome: "Acolhimento",
        desc: "Recepção interna e integração de visitantes",
        funcoes: ["Conduzir ao Acolhimento", "Recepcionar", "Servir", "Preparar a mesa"],
        cor: "#D9A752",
        themeClass: "theme-acolhimento",
        icon: "fa-solid fa-heart",
        tipo: "hibrido",
        categoria: "hibrido",
        labelMembroSingular: "Obreiro",
        labelMembroPlural: "Obreiros",
        participaCulto: true,
        possuiEscala: true,
        possuiReposicao: true,
        possuiEstoque: false,
        possuiCheckinCulto: true,
        possuiFechamentoCulto: true,
        possuiInicioServico: false,
        possuiFimServico: false
    },
    'escala_livre': {
        nome: "Escala Livre",
        desc: "Escala geral livre sem setor definido",
        funcoes: ["Escala Livre"],
        cor: "#6B7280",
        themeClass: "theme-diaconia",
        icon: "fa-solid fa-users",
        tipo: "liturgico",
        categoria: "liturgico",
        labelMembroSingular: "Obreiro",
        labelMembroPlural: "Obreiros",
        participaCulto: true,
        possuiEscala: true,
        possuiReposicao: false,
        possuiEstoque: false,
        possuiCheckinCulto: true,
        possuiFechamentoCulto: true,
        possuiInicioServico: false,
        possuiFimServico: false
    },
    'limpeza': {
        nome: "Limpeza",
        desc: "Limpeza e Conservação",
        funcoes: ["Limpeza geral", "Salão e banheiros", "Áreas externas", "Reposição de produtos"],
        cor: "#14b8a6",
        themeClass: "theme-limpeza",
        icon: "fa-solid fa-broom",
        tipo: "operacional",
        tipoOperacao: 'continua',
        categoria: "operacional",
        labelMembroSingular: "Voluntário",
        labelMembroPlural: "Voluntários",
        participaCulto: false,
        possuiEscala: true,
        possuiReposicao: true,
        possuiEstoque: true,
        possuiCheckinCulto: false,
        possuiFechamentoCulto: false,
        possuiInicioServico: true,
        possuiFimServico: true
    },
    'manutencao': {
        nome: "Manutenção",
        desc: "Manutenção Predial e Reparos",
        funcoes: ["Manutenção geral", "Reparo elétrico", "Reparo hidráulico", "Pintura", "Outros"],
        cor: "#F59E0B",
        themeClass: "theme-diaconia",
        icon: "fa-solid fa-screwdriver-wrench",
        tipo: "operacional",
        tipoOperacao: 'continua',
        categoria: "operacional",
        labelMembroSingular: "Voluntário",
        labelMembroPlural: "Voluntários",
        participaCulto: false,
        possuiEscala: true,
        possuiReposicao: true,
        possuiEstoque: true,
        possuiCheckinCulto: false,
        possuiFechamentoCulto: false,
        possuiInicioServico: true,
        possuiFimServico: true
    }
};
